### ISSUE TITLE
Documentation sur la modélisation

### ISSUE THREAD

**Issue by fvanhoutte** [etalab/schema-amenagements-cyclables#14]
Bonjour,

- Est il prévu d'étayer la documentation sur la description de la modélisation conceptuelle de la base de données  à l'image des standards CNIG ?

- Dans le même ordre, s'agissant d'une donnée géographique, je note l'absence de toute référence à la question de la modélisation géométrique des aménagements (topologie, règles de saisie...). C'est dangereux de ne pas fixer de cadre sur ce point, même si la lecture du schéma json donne quelques indications (1 objet par axe semble t-il).

**Comment by Miryad3108** [comment]
Bonjour, 

Nous allons publier une documentation afin de faciliter la prise en main de l'outil par les producteurs de données. Vous y trouverez notamment des indications sur les règles de saisie, les cas particuliers comme les aménagements sur sites propres etc.. 
Je reviendrai vers vous ultérieurement avec la date de publication.

**Comment by Miryad3108** [comment]
Bonjour @fvanhoutte , 

Vous trouverez le guide d'aide à la numérisation éditée par Vélo & Territoires ici : https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/guide-de-numerisation

N'hésitez pas à nous faire des retours.

**Comment by fvanhoutte** [comment]
Vu merci.
Juste une remarque, ça me semble un peu cavalier de glisser dans une doc de spéc de numérisation, le guide d'utilisation d'un outil particulier. Si vous souhaitez au final, en passer par le CNIG, il faudra revoir ce point et spitter spéc et doc d'une app.

Cordialement

**Comment by Miryad3108** [comment]
Bonjour, 

Nous ne passerons pas par le CNIG pour ce schéma. 
Ce guide de numérisation permet de revenir sur la numérisation d'aménagements spécifiques. L'outil "WebSIG" a été développé par Vélo & Territoires pour faciliter la production de ces données mais la collectivité peut également produire les données avec des outils internes ou sur OpenStreetMap.

Bien à vous,
