### ISSUE TITLE
Formats des gabarits de saisie et script d'implémentation

### ISSUE THREAD

**Issue by fvanhoutte** [etalab/schema-amenagements-cyclables#15]
Bonjour,

Est il prévu pour la communauté géomatique des collectivité territoriales qui pratiquent usuellement les standards CNIG, de proposer des gabarits de saisie SHP, ou mieux en complément, un script SQL permettant d'implémenter le modèle de données en base relationnelle ?

Merci

**Comment by fcommeaux** [comment]
Bonjour,
Oui c'est prévu, vous trouverez dans les jours à venir un script SQL et un template shp (avec formulaire de saisie qgis) sur ce dépôt Github.
Cordialement,

**Comment by fvanhoutte** [comment]
auto close suite à ressources placées dans le répertoire tools
