### ISSUE TITLE
Choix de la licence

### ISSUE THREAD

**Issue by fvanhoutte** [etalab/schema-amenagements-cyclables#16]
Bonjour,

Il est proposé à défaut une licence ODBL là où pour d'autre données le choix semble porter sur la LOV2.
Pourquoi ce choix dans le cas présent ? Par nécessité d'héritage pour une donnée source en provenance de OSM ?

Cordialement

**Comment by bchartier** [comment]
À mon humble avis, la question de la licence des données est hors sujet dans une spécification qui concerne un modèle de données. Chaque producteur de base de données doit être libre de choisir la licence qui lui convient (de préférence en respectant le cadre réglementaire auquel ce jeu de données est soumis). Imposer ODbL à tous les producteur n'a pas de sens. On sent bien que c'est la volonté de certains acteurs de pouvoir réintégrer toutes ces données dans une base de données centralisée mais cela n'a rien a faire dans ce projet de schéma à mon avis.

**Comment by NicolasBerthelot** [comment]
Bonjour, 

Vos commentaires sont tout à fait justes. Effectivement il n'y a aucune raison de préciser dans le schéma la licence de données associée aux données.

Je me permets de préciser ici qu'en revanche nous pouvons déjà indiquer que la base nationale issue de l'assemblage des différents fichiers locaux sera en [ODbL avec les conditions particulières qui ont été précisées par le Point d'Accès National](https://doc.transport.data.gouv.fr/reutilisateurs/licence-odbl-et-conditions-de-reutilisation). Ces conditions précisent les critères de repartage des données. Le repartage des données à l'identique n'est attendu que pour des données de même nature, même granularité et même couverture spatiale. 
Pour les données issues d'OpenStreetMap la licence ODbL sans conditions particulières s'appliquera.
Au niveau local il sera donc tout à fait possible d'utiliser la Licence Ouverte.

**Comment by bchartier** [comment]
Merci.
