### ISSUE TITLE
Champs optionnels

### ISSUE THREAD

**Issue by bchartier** [etalab/schema-amenagements-cyclables#22]
Le README du projet indique pour les champs optionnels (cf. https://github.com/etalab/schema-amenagements-cyclables/blob/master/README.md#format-de-fichier) : "La colonne doit toutefois être présente."
Je ne pense pas que ce soit utile. Le format JSON est justement un format souple qui n'impose pas ce genre de chose (il me semble). Si vous voulez conserver cette clause :
* Il faudrait ne pas utiliser le terme "colonne" qui n'est pas un terme utilisée pour des fichiers JSON.
* il faudrait peut-être (c'est pas nécessaire si l'on s'en tient aux spécifications de JSON je pense) éclairer le lecteur en précisant qu'il faudrait avoir quelque chose du genre `"reseau_loc": null` dans le fichier GeoJSON.

**Comment by Miryad3108** [comment]
Bonjour, 

Merci pour votre retour. Le mot colonne n'est effectivement pas approprié et nous l'avons remplacer par terme mot "champ". Nous tenons à ce que tous les champs optionnels soient présents même si ils sont vides car cela nous facilitera l'agrégation des données dans une base nationale.
