### ISSUE TITLE
Champs contenant des listes de valeurs

### ISSUE THREAD

**Issue by bchartier** [etalab/schema-amenagements-cyclables#23]
Lors de la présentation du schéma en webinaire aujourd'hui  un certain de nombre de champs ont été présentés comme étant des chaînes de caractères contenant des listes de valeurs séparées par des `:`. Le schéma confirme cela dans la description du champ num_iti :
```
                            "num_iti": {
                                "type": "array",
                                "description": "Numéro des itinéraires, des EuroVelo au schéma départementaux, auxquels le segment appartient. Séparé par « : »",
                                "examples": [
                                    "0001:",
                                    "0006:",
                                    "0045:"
                                ]
                            },
```

Mais le type du champ tel que documenté dans le schéma est un `array`.
Et dans l'exemple de JSON valide fourni on a :
```
                "num_iti": [
                    "0001:",
                    "0006:",
                    "0045:"
                ],
```

Que doit-on comprendre au final ?

**Comment by Miryad3108** [comment]
Bonjour, 
Nous vous remercions de nous avoir remonté cette erreur. Nous avons modifié la propriété du champ : c'est une chaîne de caractère qui est attendue .

![image](https://user-images.githubusercontent.com/59559301/109621148-fe516980-7b3a-11eb-9584-5744d395944d.png)

**Comment by bchartier** [comment]
Je ferme ce ticket alors...
