### ISSUE TITLE
Comprendre pourquoi le schéma ne s'affiche pas sous forme de table sur schema.data.gouv

### ISSUE THREAD

**Issue by fchabouis** [etalab/schema-amenagements-cyclables#25]
Voir https://schema.data.gouv.fr/etalab/schema-amenagements-cyclables/latest.html

par comparaison avec https://schema.data.gouv.fr/etalab/schema-stationnement/latest/documentation.html

**Comment by johanricher** [comment]
La raison est tout simple : pour générer un tel tableau de documentation du schéma, schema.data.gouv.fr repose sur la librairie [table-schema-to-markdown](https://pypi.org/project/table-schema-to-markdown/) qui, comme son nom l'indique, utilise le format Table Schema.

C'est d'ailleurs pour cela qu'il avait été recommandé de faire le choix de Table Schema pour l'écriture du schéma `schema-amenagements-cyclables`. L'écosystème d'outils déjà disponibles et conçus pour les schémas open data (création, validation, documentation...), et bien sûr la communauté qui va avec, sont très appréciables pour les utilisateurs (cf. [cette discussion](https://github.com/etalab/schema-amenagements-cyclables/issues/4#issuecomment-742038937)).
