### ISSUE TITLE
Définition de l'identifiant unique (id_local)

### ISSUE THREAD

**Issue by bferretti57** [etalab/schema-amenagements-cyclables#27]
Bonjour, 

Merci pour ce nouveau standart et la présentation du 29/01 qui facilite la compréhension des modifications à effectuer par les producteurs de données.

L'identifiant unique "Id_local" est à définir par la collectivité. A défaut d'un standard, est-ce qu'un minimum de caractères est recommandé afin d'éviter des doublons? 
Que se passe t'il le cas échéant où des collectivités à l'acronyme similaire (par exemple - Montpellier Méditerranée Métropole et Metz Métropole) renseigneraient des objets avec un identifiant local identique (par exemple - MM138)?

Merci de vos réponses,

**Comment by fcommeaux** [comment]
Bonjour et merci pour cette question.
Effectivement l'id_local pourrait ne pas être unique à l'échelle nationale. Cela ne posera pas de problème car au moment de l'agrégation des données, le PAN attribuera un identifiant national unique à tous les aménagements. Il n'y a donc pas de recommandation d'utilisation du champ id_local, que chaque collectivité peut utiliser selon ses propres règles.
