### ISSUE TITLE
Coquilles dans le fichier schema_amenagements_cyclables.json

### ISSUE THREAD

**Issue by touteslatitudes** [etalab/schema-amenagements-cyclables#28]
Juste signaler 2 coquilles dans le fichier  schema_amenagements_cyclables.json : https://github.com/etalab/schema-amenagements-cyclables/blob/master/schema_amenagements_cyclables.json

AMENAGEMENT MIXTE PIETON VELO HORS VOIE VERTE plutôt que AMENAGEMENT MIXTES PIETON VELO HORS VOIE VERTE

ACCOTEMENT REVETU HORS CVCB plutôt que ACCOTEMENT REVENTU HORS CVCB

**Comment by Miryad3108** [comment]
Bonjour, 

Je vous remercie pour ces corrections. Les modifications ont bien été reportées dans le fichier schema_amenagements_cyclables.json
