### ISSUE TITLE
Ajouter un champ Surface

### ISSUE THREAD

**Issue by MathiasVadot** [etalab/schema-amenagements-cyclables#29]
Dans une nouvelle version du schéma, il serait intéressant d'ajouter un champs surface / revêtement, très utile pour distinguer les voies vertes revêtues en stabilisé de celles revêtues en revêtement lisse type asphalte.
A discuter avec le groupe de travail ?

**Comment by Miryad3108** [comment]
Bonjour Mathias, 
Ce champ était proposé dans la première version du schéma mais n'a pas été retenu par le groupe de travail car l'information n'a pas été jugée importante par les réutilisateurs ni essentiel par les producteurs. 
Vous pouvez toutefois faire une demande d'amélioration du schéma grâce à une Pull Request (PR) afin de proposer un nouveau vote pour ce champ. Voici le [tutoriel pour faire une PR](https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables)

**Comment by MathiasVadot** [comment]
Bonjour, merci pour votre retour, je viens de faire un Pull Request je ne sais pas si il est bien passé. J'ai rajouté un champs revetement_d et revetement_g avec comme choix ; LISSE / RUGUEUX / MEUBLE comme dans le géostandard véloroute et voie verte de Vélo et Territoire.

Peut être mettre un champs vierge pour ne pas avoir à renseigner la donnée pour des aménagement cyclables sur chaussée.

Après avoir voulu utiliser ce standard, j'ai vite été confronté au problème de la classification des voies vertes et chemin mixte piéton, dont la nature et la qualité du revêtement est une variable essentiel.

**Comment by Miryad3108** [comment]
Bonjour Mathias, 
La Pull Request n'apparaît pas. Vous avez rencontré des difficultés particulières quand vous avez voulu la faire ? 
Nous pouvons prévoir un appel pour comprendre pourquoi elle n'a pas été publiée.

**Comment by Miryad3108** [comment]
Demande faite sous forme de Pull request : je ferme l'issue
