### ISSUE TITLE
Signification du champ acces_ame

### ISSUE THREAD

**Issue by Ynn-Gl** [etalab/schema-amenagements-cyclables#40]
Bonjour,
Le champ acces_ame est définit comme suit : Accessibilité des aménagements par type de véhicule non motorisé".
Peut-on le rendre multivalué, comme nom_loc et num_iti ? Car l'accessibilité peut être multiple.
Ou alors, peut-être n'ai-je pas bien compris l'objet de ce champ ?
Merci d'avance,

**Comment by Miryad3108** [comment]
Bonjour, 

Nous considérons que si vous choisissez "Roller" comme type de véhicule non motorisé c'est que l'aménagement est accessible pour tous les autres types de véhicules de la liste. Si vous choisissez "VTC" c'est que l'aménagement est aussi accessible aux "VTT".

L'ordre des véhicules vient d'être modifié et ils sont maintenant listé comme suit : 
- Roller 
- Vélo de route 
- VTC 
- VTT

Est-ce plus clair ainsi ? 


Bien à vous,

**Comment by Ynn-Gl** [comment]
Ok, c'est noté. Merci !
