### ISSUE TITLE
Que veut dire la valeur REV dans reseau_loc ?

### ISSUE THREAD

**Issue by Ynn-Gl** [etalab/schema-amenagements-cyclables#41]
Bonjour,

Que veut dire la valeur possible "REV" dans reseau_loc définissant le type de réseau local ( 3 valeurs possibles REV, STRUCTURANT et AUTRE) ?

Merci d'avance,

**Comment by bferretti57** [comment]
Bonjour, 

Cela signifie Réseau express vélo. 
Bonne journée,

**Comment by Ynn-Gl** [comment]
Ah merci !
