### ISSUE TITLE
Pull request "MARQUAGES AU SOL"

### ISSUE THREAD

**Issue by MichaelSIOCA** [etalab/schema-amenagements-cyclables#47]
Ajout d'une modalité "MARQUAGES AU SOL" aux champs ame_d et ame_g pour pouvoir intégrer les aménagements cyclables prévus par le code de l'environnement pour les rues à sens unique et à une seule file (Article L228-2).
Seul les marquages répertoriées par l'instruction interministérielle sur la signalisation routière (7ème partie) peuvent être pris en compte (figurines vélo, double chevrons, figurine vélo accompagnée d’une flèche directionnelle, association de ces éléments).
Le terme "Marquages au sol" est celui utilisé dans le code.

https://github.com/etalab/schema-amenagements-cyclables/pull/46

![image](https://user-images.githubusercontent.com/78017406/130029751-52b1cfa8-66d4-4793-9ec0-c2ad085ba44c.png)

**Comment by Miryad3108** [comment]
La demande a été soumise sous forme de Pull Request, je ferme l'issue.
